version: "3.9"
services:
  backend:
    build: ./app
    stdin_open: true
    depends_on:
      - db
    environment:
      STAGE: test
      SQLALCHEMY_DATABASE_URI: postgresql://postgres:michael1226@database:5432/Face_Wallet_1
    networks:
      - default
    ports:
      - "5000:5000"
    #restart: always
  db:
    container_name: database
    build:
      context: ./db
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: michael1226
      POSTGRES_DB: Face_Wallet_1
    networks:
      - default
    ports:
      - 5432:5432
    #restart: always
    #volumes:
      #- ./postgres-data:/var/lib/postgresql/data
      #- ./postgres-data:/docker-entrypoint-initdb.d/
